### ISSUE TITLE
按照文档配置好了编译报错

### ISSUE THREAD

**Issue by xieyimaple** [ant-design/antd-moment-webpack-plugin#10]
UmiJS 4 项目，以下是配置信息以及错误信息：
配置：
chainWebpack(config) {
    config.plugin('antd-moment')
    .use(new AntdMomentWebpackPlugin())
}
报错：
error - ./node_modules/@ant-design/pro-field/es/components/DatePicker/index.js:10:0-49
Module not found: Error: Can't resolve 'dayjs/plugin/weekOfYear' in 'D:\project\vrmfront\node_modules\@ant-design\pro-field\es\components\DatePicker'
error - ./node_modules/@ant-design/pro-field/es/components/FromNow/index.js:6:0-53
Module not found: Error: Can't resolve 'dayjs/plugin/relativeTime' in 'D:\project\vrmfront\node_modules\@ant-design\pro-field\es\components\FromNow'
error - ./node_modules/@ant-design/pro-field/es/index.js:41:0-43
Module not found: Error: Can't resolve 'dayjs/plugin/weekday' in 'D:\project\vrmfront\node_modules\@ant-design\pro-field\es'
error - ./node_modules/@ant-design/pro-field/es/index.js:42:0-49
Module not found: Error: Can't resolve 'dayjs/plugin/localeData' in 'D:\project\vrmfront\node_modules\@ant-design\pro-field\es'
error - ./node_modules/@ant-design/pro-utils/es/conversionMomentValue/index.js:5:0-55
Module not found: Error: Can't resolve 'dayjs/plugin/quarterOfYear' in 'D:\project\vrmfront\node_modules\@ant-design\pro-utils\es\conversionMomentValue'

**Comment by jiajiaxing1** [comment]
我也遇到这个问题了 有什么解决方案吗？

**Comment by afc163** [comment]
See https://github.com/ant-design/antd-moment-webpack-plugin/pull/4

**Comment by afc163** [comment]
Resolved in https://github.com/ant-design/antd-moment-webpack-plugin/commit/d9e52c54d4eb18063e89095bb6302890a7add6e0
