### ISSUE TITLE
Module not found: Error: Can't resolve 'dayjs/plugin/weekOfYear' in '/Users/jiajiaxing/Desktop/zhengan/sovell-mage-management-handlefraud-umi4/node_modules/@ant-design/pro-field/es/components/DatePicker'

### ISSUE THREAD

**Issue by jiajiaxing1** [ant-design/antd-moment-webpack-plugin#12]
umi3升级成umi4之后，顺便升级了antd5，配置兼容插件之后报错
// config/config.ts
chainWebpack(memo, args) {
    memo.module
      .rule('media')
      .test(/\.(mp3|4)$/)
      .use('file-loader')
      .loader(require.resolve('file-loader'));

    memo.plugin('AntdMomentWebpackPlugin').use(new AntdMomentWebpackPlugin());
  },

报错信息
 ./node_modules/@ant-design/pro-field/es/components/DatePicker/index.js:7:0-49
Module not found: Error: Can't resolve 'dayjs/plugin/weekOfYear' in '/Users/jiajiaxing/Desktop/zhengan/sovell-mage-management-handlefraud-umi4/node_modules/@ant-design/pro-field/es/components/DatePicker'
error - ./node_modules/@ant-design/pro-field/es/components/FromNow/index.js:6:0-53
error - ./node_modules/@ant-design/pro-field/es/index.js:45:0-57
error - ./node_modules/@ant-design/pro-field/es/index.js:46:0-43
error - ./node_modules/@ant-design/pro-field/es/index.js:47:0-49
error - ./node_modules/@ant-design/pro-field/es/index.js:48:0-43
error - ./node_modules/@ant-design/pro-field/es/index.js:49:0-49
error - ./node_modules/@ant-design/pro-utils/es/conversionMomentValue/index.js:3:0-55
error - ./node_modules/@ant-design/pro-utils/es/parseValueToMoment/index.js:2:0-63
Module not found: Error: Can't resolve 'dayjs/plugin/relativeTime' in '/Users/jiajiaxing/Desktop/zhengan/sovell-mage-management-handlefraud-umi4/node_modules/@ant-design/pro-field/es/components/FromNow'
Module not found: Error: Can't resolve 'dayjs/plugin/advancedFormat' in '/Users/jiajiaxing/Desktop/zhengan/sovell-mage-management-handlefraud-umi4/node_modules/@ant-design/pro-field/es'
Module not found: Error: Can't resolve 'dayjs/plugin/isoWeek' in '/Users/jiajiaxing/Desktop/zhengan/sovell-mage-management-handlefraud-umi4/node_modules/@ant-design/pro-field/es'
Module not found: Error: Can't resolve 'dayjs/plugin/localeData' in '/Users/jiajiaxing/Desktop/zhengan/sovell-mage-management-handlefraud-umi4/node_modules/@ant-design/pro-field/es'
Module not found: Error: Can't resolve 'dayjs/plugin/weekday' in '/Users/jiajiaxing/Desktop/zhengan/sovell-mage-management-handlefraud-umi4/node_modules/@ant-design/pro-field/es'
Module not found: Error: Can't resolve 'dayjs/plugin/weekOfYear' in '/Users/jiajiaxing/Desktop/zhengan/sovell-mage-management-handlefraud-umi4/node_modu

**Comment by Carl0608** [comment]
加 一

**Comment by Qiuhang817385** [comment]
memo.plugin('AntdMomentWebpackPlugin').use(new AntdMomentWebpackPlugin(),[{
disableDayjsAlias:true
}]); 
试一下

**Comment by Janesuyue** [comment]
你好，最后解决了嘛

**Comment by jiajiaxing1** [comment]
> 你好，最后解决了嘛

没有，最后全局替换的 你可以试试楼上同学的提供的

**Comment by FlyAboveGrass** [comment]
可以看下这个[issue](https://github.com/ant-design/antd-moment-webpack-plugin/pull/4)。最后我的解决方案是给插件多加了一个配置： new AntdMomentWebpackPlugin({ disableDayjsAlias: true })

**Comment by Birditch** [comment]
> 可以看下这个[issue](https://github.com/ant-design/antd-moment-webpack-plugin/pull/4)。最后我的解决方案是给插件多加了一个配置： new AntdMomentWebpackPlugin({ disableDayjsAlias: true })

具体怎么弄的？

**Comment by FlyAboveGrass** [comment]
> > 可以看下这个[issue](https://github.com/ant-design/antd-moment-webpack-plugin/pull/4)。最后我的解决方案是给插件多加了一个配置： new AntdMomentWebpackPlugin({ disableDayjsAlias: true })
> 
> 具体怎么弄的？

就是加了这个 webpack 的配置呀

**Comment by afc163** [comment]
See https://github.com/ant-design/antd-moment-webpack-plugin/pull/4

**Comment by afc163** [comment]
Resolved in https://github.com/ant-design/antd-moment-webpack-plugin/commit/d9e52c54d4eb18063e89095bb6302890a7add6e0
