### ISSUE TITLE
Cannot compile project that uses @ant-design/pro-components

### ISSUE THREAD

**Issue by Bosseskompis** [ant-design/antd-moment-webpack-plugin#2]
**Steps to reproduce:**
1. Compile a project that uses ProList

`webpack 5.75.0 compiled with 5 errors`

`ERROR in ./node_modules/@ant-design/pro-field/es/components/DatePicker/index.js 9:0-49
Module not found: Error: Can't resolve 'dayjs/plugin/weekOfYear'`

`ERROR in ./node_modules/@ant-design/pro-field/es/components/FromNow/index.js 7:0-53
Module not found: Error: Can't resolve 'dayjs/plugin/relativeTime'`

`ERROR in ./node_modules/@ant-design/pro-field/es/index.js 42:0-43
Module not found: Error: Can't resolve 'dayjs/plugin/weekday'`

`ERROR in ./node_modules/@ant-design/pro-field/es/index.js 43:0-49
Module not found: Error: Can't resolve 'dayjs/plugin/localeData'`

`ERROR in ./node_modules/@ant-design/pro-utils/es/conversionMomentValue/index.js 5:0-55
Module not found: Error: Can't resolve 'dayjs/plugin/quarterOfYear'`

**Comment by snaptsoft** [comment]
This appears to still be happening when using `craco` to modify the webpack config with `antd@5.1.6`, `@ant-design/pro-layout@7.6.1`. Error message received: 
```
Failed to compile.

Module not found: Error: Can't resolve 'dayjs/plugin/quarterOfYear' in 'C:\Users\user\WebDev\project\client\node_modules\@ant-design\pro-utils\es\conversionMomentValue'
ERROR in ./node_modules/@ant-design/pro-utils/es/conversionMomentValue/index.js 5:0-55
Module not found: Error: Can't resolve 'dayjs/plugin/quarterOfYear' in 'C:\Users\user\WebDev\project\client\node_modules\@ant-design\pro-utils\es\conversionMomentValue'

webpack compiled with 1 error
```
Below is the craco config. 
```js
// craco.config.js
const AntdMomentWebpackPlugin = require("@ant-design/moment-webpack-plugin");

module.exports = {
  webpack: {
    configure: (webpackConfig) => ({
      ...webpackConfig,
      plugins: [new AntdMomentWebpackPlugin()],
    }),
  },
};

```
